

name: Continuous

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]




jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        build_type: ['appimage', 'snap', 'deb', 'rpm']
        arch: ['x64', 'ia32', 'armv7l', 'arm64']
        exclude:
          - build_type: snap
            arch: 'arm64'
          - build_type: snap
            arch: 'armv7l'
    steps:
      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Snapcraft
        if: matrix.build_type == 'snap'
        run: sudo snap install snapcraft --classic

      - name: Setup build environment
        run: |
          ./src/scripts/ci-setup-linux.sh

      - name: Build
        run: |
          cd src
          yarn run build:${{ matrix.build_type }} --${{ matrix.arch }}

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Musicblocks-${{ matrix.arch }}-${{ matrix.build_type }}
          path: 'src/dist/'

  build-macos:
    runs-on: macos-latest
    steps:
      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      
      - name: Setup build environment
        run: |
          ./src/scripts/ci-setup-macos.sh

      - run: |
          cd src
          yarn run build:macos

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Musicblocks-macos-x86_64
          path: 'src/dist/'

  build-windows:
    strategy:
      matrix: 
        arch: ['x64', 'ia32']
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      
      - name: Setup build environment
        run: |
          .\src\scripts\ci-setup-windows.bat

      - run: |
          cd src
          yarn run build:windows --${{ matrix.arch }}

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Musicblocks-windows-x86_64
          path: 'src/dist/'

  Release:
    needs: [build, build-macos, build-windows]
    runs-on: ubuntu-latest


    steps:
    - name: Make a directory to store all artifacts
      run: mkdir artifacts
    - uses: actions/download-artifact@v2
      with:
        path: artifacts


    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      if: github.ref == 'refs/heads/master'
      with:
        automatic_release_tag: continuous
        title: continuous
        files: |
          artifacts/*
        repo_token: ${{ secrets.GITHUB_TOKEN }} 
