

name: Continuous

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]




jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        arch: ['x64', 'ia32', 'armv7l', 'arm64']
        build_type: ['appimage', 'snap', 'deb', 'rpm', 'windows', 'macos']

    steps:
      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      
      - name: Setup build environment
        run: |
          ./src/scripts/ci-setup-linux.sh

      - run: |
          cd src
          yarn run build:${{ matrix.build_type }} --${{ matrix.arch }}

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Musicblocks-${{ matrix.arch }}-${{ matrix.build_type }}
          path: 'src/dist/'


  Release:
    needs: [build]
    runs-on: ubuntu-latest


    steps:
    - name: Make a directory to store all artifacts
      run: mkdir artifacts
    - uses: actions/download-artifact@v2
      with:
        path: artifacts


    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      if: github.ref == 'refs/heads/master'
      with:
        automatic_release_tag: continuous
        title: continuous
        files: |
          artifacts/*
        repo_token: ${{ secrets.GITHUB_TOKEN }} 
